config/routes.rb
VallaYAviso::Application.routes.draw do
  
  resources :difficulty_quotes

  resources :types_descriptions
  resources :types
  resources :categories
  
  resources :agencies do
    get 'search', on: :collection
  end

  resources :binnacles do
  end

  resources :production_orders do
    get 'search', on: :collection
    get 'quotes_lists', on: :collection
    get 'new_orders', on: :collection
    get 'details', on: :member
    get 'review', on: :member
    get 'sent_to_cost', on: :member
    get 'sent_to_cost_by_price_adjustment', on: :member
    get 'sent_to_production', on: :member
    get 'ended', on: :member
    get 'ended_inventory', on: :member
    get 'ended_machine', on: :member
    get 'ended_warehouse', on: :member
    get 'billing', on: :member     
    get 'billed', on: :member     
    get 'list' => 'production_orders#list'
    resources :production_order_binnacles
  end

  resources :bills do
      get 'search', on: :collection
    end

  resources :remissions do
      get 'search', on: :collection
      get 'sent', on: :member 
    end

  resources :work_orders  do
    get 'search', on: :collection
    get 'deliver', on: :member 
    get 'validate', on: :member 
  end

  resources :quotes do
    get 'search', on: :collection    
    get 'details', on: :member 
    get 'customer_review', on: :member 
    get 'sent_to_cost', on: :member   
    get 'back_to_sales', on: :member 
    get 'canceled', on: :member 
    get 'quote_prices', on: :member 
    put 'sent_seller', on: :member 
    get 'delivered_customer', on: :member 
    get 'approved', on: :member 
    get 'rejected', on: :member 
    get 'cost_report', on: :member 
    get 'costs' => 'quotes#costs', :as => 'costs_registration'  
    put 'costs' => 'quotes#update_costs', :as => 'put_costs_registration'  
    post 'clients' => 'quotes#create_client',   on: :collection      
    get 'list_cost', on: :collection 
  end

  resources :product_orders_materiales do

  end

  resources :products do
    get 'show_category', on: :member 
  end

  resources :product_types do
    get 'show_product', on: :member 
  end 

  resources :products do
    get 'show_category', on: :member 
  end  

  resources :materials_lists do
    get 'sent_to_production', on: :member   
    get 'sent_to_store', on: :member 
  end

  get 'alerts' => 'alerts#show', :as => 'alerts'
  put 'alerts/:id' => 'alerts#update', :as => 'alerts_update'

  resources :departments
  resources :clients
  resources :advisers
  resources :comments 
  resources :materiales
  resources :types_descriptions

  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

   namespace :admin do
    resources :user
  end

   

  root 'welcome#index'

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:customer_review, :sent_to_cost, :back_to_sales, :canceled, :quote_prices, :sent_seller, :delivered_customer,  :approved, :rejected, :cost_report, :show, :edit, :update, :destroy, :details]
  before_action :configure_list

  # GET /quotes
  # GET /quotes.json
  def index
    if current_user.is?(:costo) && !current_user.is?(:admin)
       @quotes = Quote.where("status in ('sent_to_cost','quote_prices') and coordinator_id is null ")
    elsif current_user.is?(:vendedor) && !current_user.is?(:admin)
       @quotes = Quote.where(administrador_id: current_user.id)
    else
       @quotes = Quote.all
    end
    #@quotes = Quote.joins('LEFT OUTER JOIN clients  ON clients.id = quotes.client_id').select('quotes.id, quotes.created_at, quotes.status, clients.name').reorder('')
    #@quotes = Quote.joins("left outer join status_quotes on status_quotes.quote_id=quotes.id").select('status_quotes.*, quotes.*').reorder('')
  end

  def list_cost
    if current_user.is?(:admin) 
      @quotes = Quote.all
    elsif !current_user.is?(:analista) 
      @quotes = Quote.where("status in ('sent_to_cost','quote_prices', 'delivered_customer', 'approved', 'rejected', 'sent_seller', 'back_to_sales')")
    elsif current_user.is?(:analista) 
      @quotes = Quote.where("status in ('sent_to_cost','quote_prices', 'delivered_customer', 'approved', 'rejected', 'sent_seller', 'back_to_sales')").where(coordinator_id: current_user.id)
    end    
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @detalle = @quote_details = QuoteDetail.joins('LEFT OUTER JOIN products  ON products.id = quote_details.product_id').select('quote_details.id, quote_details.quantity, quote_details.price, quote_details.description, quote_details.product_id, quote_details.specificationes, products.name').where(quote_id: params[:id])
    #byebug
    respond_to do |format|
      format.html { render action: 'show' }
      format.pdf { render pdf: "presupuesto_#{params[:id]}" }
    end

  end

  def details
    @quote_detail = {"id" => @quote.id, 
                      "agency_name" => @quote.agency.try(:name), 
                      "date" => @quote.try(:created_at),
                      "client_name" => @quote.client.try(:name), 
                      "client_phone" => @quote.client.try(:phone), 
                      "adviser_name" => @quote.adviser.try(:name), 
                      "adviser_assessor_code" => @quote.adviser.try(:assessor_code),                       
                      "adviser_agency_id" => @quote.adviser.try(:agency_id),                       
                      "commission_quote" => @quote.try(:commission_quote), 
                      "client_nit" => @quote.client.try(:nit), 
                      "client_address" => @quote.client.try(:address), 
                      "quote_status" => @quote.try(:status), 
                      "quote_reference" => @quote.try(:reference)}  
    
    respond_to do |format|  ## Add this
      format.json { render json: @quote_detail , status: :ok}
    end 
  end

  # GET /quotes/new
  def new    
    @quote = Quote.new
    @detalle = @quote.quote_details
    @quote.quotes_anexes.build 
    @client = Client.new  

  end

  # GET /quotes/1/edit
  def edit
    @quote.quote_details
    if @quote.quotes_anexes.count > 0
      @quote.quotes_anexes
      #byebug
    else
      @quote.quotes_anexes.build 
    end  
    #@detalle = QuoteDetail.where(quote_id: params[:id]).order(id: :asc) 
    @detalle = @quote_details = QuoteDetail.joins('LEFT OUTER JOIN products  ON products.id = quote_details.product_id').select('quote_details.id, quote_details.quantity, quote_details.price, quote_details.description, quote_details.specificationes, quote_details.product_id, products.name').where(quote_id: params[:id])

  end

    # GET /quotes/1/costs
  def costs   
    @quote = Quote.find(params[:quote_id])      
    @detalle = QuoteDetail.joins(:product).where(quote_id: params[:quote_id])

    # save firt time analist came in.   
    if @quote.begin_analysis.nil? && current_user.is?(:analista) && @quote.coordinator_id == current_user.id && !current_user.is?(:admin)
      @quote.begin_analysis = Time.now
      @quote.save
    end 
   
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update_costs
    respond_to do |format|      
      @quote = Quote.find(params[:quote_id]) 
      @quote.validates_cost=true
      if @quote.update(quote_params)  

        if @quote.sent_to_cost? 
           @quote.quote_prices!  
           StatusQuote.create :status =>@quote.status, :quote_id =>@quote.id , :administrador_id =>current_user.id
           ActionCorreo.cotizacion_email_costos(@quote.id, current_user).deliver
           format.html { redirect_to list_cost_quotes_path, notice: 'Los Costos de la Cotización se actualizaron satisfactoriamente.' }
           format.json { head :no_content }           

        elsif @quote.quote_prices?
          #proceso para validar la fecha
          @quote.validates_cost=false
       
          if @quote.estado_cost == 'Se Incumplio'
            @quote.validates_sent_seller=true 
          else
            @quote.validates_sent_seller=false      
          end
            
          #byebug
          if @quote.sent_seller!
            StatusQuote.create :status =>@quote.status, :quote_id =>@quote.id , :administrador_id =>current_user.id              
            format.html { redirect_to list_cost_quotes_path, notice: 'La Cotizacion fue enviada a Ventas.'  }
            format.json { head :no_content }
          else
            format.html { redirect_to list_cost_quotes_path, notice: 'La Cotizacion No pudo ser enviada, Verifique que dejo la observacion por demora en el envio.'  }
          end
        end

      ##fin
      else
        format.html { render action: 'costs' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end  

  # GET /quotes/search
  def search
    @quotes = Quote.search_by_query(params[:search])
    render :index
  end


  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.validates_cost=false
    @quote.validates_sent_seller=false
    @quote.administrador = current_user
    respond_to do |format|
      if @quote.save
       StatusQuote.create :status =>@quote.status, :quote_id =>@quote.id , :administrador_id =>current_user.id
        if  params[:quote]['quotes_anexes_attributes']
          params[:quote]['quotes_anexes_attributes'].each do |key, value|        
              value['anexo'].each do |picture|     
                 @quote.quotes_anexes.create(:anexo=> picture)       
              end  
          end  
        end  

      #byebug
        format.html { redirect_to quotes_path, notice: 'La Cotización fue creada satisfactoriamente.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        @detalle = @quote.quote_details
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    
    respond_to do |format|
      if @quote.update(quote_params)
       #@quote.quotes_anexes.delete_all

        id_anexos = [] 
        i=0
        if  params[:quote]['edit_anexes_attributes']
          params[:quote]['edit_anexes_attributes'].each do |key, value|        
             id_anexos[i]=value["id"]
             i=i+1
          end  
        end 

        @quotes_anexes_del = QuoteAnexes.where(quote_id: @quote.id).where.not(id: id_anexos).select('quotes_anexes.id')
        QuoteAnexes.where(id: @quotes_anexes_del).delete_all

        if  params[:quote]['quotes_anexes_attributes']
          params[:quote]['quotes_anexes_attributes'].each do |key, value|        
             if value['anexo']
                value['anexo'].each do |picture| 
                  if  picture  
                      @quote.quotes_anexes.create(:anexo=> picture)       
                  end 
                end 
             end   
          end  
        end          
        #byebug
        @quote.quote_details.delete_all
        if params[:quote]['quote_details_attributes']          
          params[:quote]['quote_details_attributes'].each do |key, value|                         
             #byebug
             @quote.quote_details.create(value)       
          end            
        end  
        format.html { redirect_to quotes_path, notice: 'La Cotización fue actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        @detalle = @quote.quote_details
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    #byebug
    @quote_details.delete_all
    @quotes_anexes.delete_all 
    #@quote.quote_details.build
    @status_quote.delete_all
    @quote.destroy        
    #byebug
    #redirect_to  
    respond_to do |format|
      format.html { redirect_to @quote, notice: 'La Cotización fue eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  #estatus de cotizacion

  #GET /quotes/:id/customer_review
  def customer_review
    if @quote.elaborated?
      @quote.customer_review!   
      StatusQuote.create :status =>@quote.status, :quote_id =>@quote.id , :administrador_id =>current_user.id  
      redirect_to quotes_path, notice: 'La Cotizacion fue Revisada por el cliente.'
    else
      render action: 'index' 
    end
  end

  #GET /quotes/:id/sent_to_cost
  def sent_to_cost
    if @quote.elaborated? or @quote.back_to_sales? 
      @quote.validates_cost=false
      @quote.validates_sent_seller=false
      @quote.sent_to_cost!    

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_filter.html.haml
= simple_form_for :search, {url: search_quotes_path, method: :get} do |f|
  .span12
    .row-fluid
      %div.span5
        = f.select :client, @clients.map{ |c| [c.name, c.id] }, label: false, prompt: "Cliente"
      %div.span5
        = f.select :adviser, @advisers.map{ |r| [r.name, r.id] }, :label => false, prompt: "Asesor"
      %div.span5
        = f.select :agency, @agencies.map{ |a| [a.name, a.id] }, :label => false, prompt: "Agencia"
    .row-fluid
      %div.span5
        = f.select :number, @quotes_list.map{ |q| [q.number, q.number] }, :label => false, prompt: "Número de la Cotización"      
      %div.span5.left-search-field   
        = f.input :reference, input_html: {class: 'width-search-field-quote', placeholder: "Referencia"}, label:false
    %div.row-fluid
      .span12.botton-filter
        = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
          - content_tag(:i, '') + "Buscar"
        = link_to(quotes_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
          - content_tag(:i, '') + "Cancelar"  

app/views/quotes/_form_anexos.html.haml
%div.span12
  .innerLR
    .widget
      .widget-head
        %h4.heading.glyphicons.settings
          %i
          = "Anexos y Fotos"
      .widget-body               
        %div
          .form-group
            = f.simple_fields_for :quotes_anexes do |quotes_anexes|
              = quotes_anexes.file_field :anexo, :class=>'file', :id=>'file-es',  :multiple => true, 'data-preview-file-type' => "any"
  .clearfix

app/views/quotes/_form_fields_anexos.html.haml
%div.span12
  .innerLR
    .widget
      .widget-head
        %h4.heading.glyphicons.settings
          %i
          = "Anexos y Fotos"
      .widget-body
        - if current_user.is?(:costo) || current_user.is?(:analista) || current_user.is?(:almacen)
          %div
            .form-group.quotes_anexes
              = f.label "Hoja de Cálculo:"
              = f.file_field :spreadsheet, :class=>'file', 'data-preview-file-type' => "any"
        %div
          .form-group.quotes_anexes
            = f.simple_fields_for :quotes_anexes do |quotes_anexes|
              = render 'quote_anexes_fields', f: quotes_anexes
            = link_to_add_association 'Agregar Nuevo Archivo', f, :quotes_anexes
  .clearfix
 

app/views/quotes/_form_fields_anexos_edit.pdf.haml
%div.span12
  .innerLR
    .widget
      .widget-head
        %h4.heading.glyphicons.settings
          %i
          = "Anexos Cotizacion"
      .widget-body                           
        %div.widget-body
          %h3="Anexos y Fotos"
          -if @quote.elaborated? or  @quote.customer_review?
            = button_tag(class: 'btn btn-icon glyphicons circle_plus btn-success add-client btn-lg', 'data-toggle' => 'modal', 'data-target' => '#myModal', 'id' => "modal-botton"){content_tag('i') + "Nuevo"}  
          %hr
          %div.tab-content
            %div.list
              %div.well  
                %table.table.table-condensed.table-striped#tabla
                  %thead
                    %tr
                      %th="Imagen"
                      %th="Nombre"  
                      %th="Tipo"                   
                      %th=""                   
                  %tbody 
                    - @quote.quotes_anexes.each_with_index do |quote_anexes, i|          
                      %tr
                        -if (quote_anexes.anexo_content_type)
                          %td
                            =image_tag quote_anexes.anexo.url, size: "52" 
                            =f.input :id, input_html: {id:"quote_edit_anexes_attributes_#{i}_id", name:"quote[edit_anexes_attributes][#{i}][id]", value:"#{quote_anexes.id}", type: 'hidden'}, label:false
                          %td=quote_anexes.anexo_file_name
                          %td=quote_anexes.anexo_content_type
                          %td=link_to "Descargar", quote_anexes.anexo.url 
                          -if @quote.elaborated? or  @quote.customer_review?
                            %td= link_to ("x"){ content_tag(:i, '', class:"icon-remove") }


  .clearfix

app/views/quotes/_form_fields_detail.html.haml
%div.span12
  .innerLR
    .widget
      .widget-head
        %h4.heading.glyphicons.settings
          %i
          = "Detalle"
      .widget-body               
        = render 'form_quote_detail', :f => f 
        %div.widget-body
          %h3="Descripción"
          %hr
          %div.tab-content
            %div.list
              %div.well.dataTables_wrapper
                %table.table-quote-details.table.table-condensed.table-striped#tabla
                  %thead
                    %tr
                      %th="Producto"  
                      %th="Observación" 
                      %th="Cantidad"                   
                      %th=""
                  %tbody
                    %tr
                      %td=''   
                      %td=''                                      
                      %td=''   
  .clearfix

app/views/quotes/_list_back.html.haml
- if @quotes.any?
  %table.table.table-condensed.table-striped#tablequotes
    %thead
      %tr
        %th="Cot"  
        %th="Asesor"  
        %th="Cliente/Agencia"
        %th="Enviado a Costos"
        %th="Inicio Costos"
        %th="Dias entrega"
        %th="Fin de Costos"
        %th="Fin real Costos"
        %th="Estado" 
        %th="Observaciones de Costo"      
        %th="Estatus"        
        %th=""
        %th=""
    %tbody
      - @quotes.each do |p|
        - sent_to_cost=' '
        - quote_prices=' '
        - sent_seller=' '  
        - dias = 0
        - quantity_difficulty = p.try(:difficulty_quote).try(:quantity)
        - p.estado.each do |x|
          -x.status=='sent_to_cost'? sent_to_cost = x.created_at : ' '
          -x.status=='quote_prices'? quote_prices = x.created_at : ' '
          -x.status=='sent_seller'? sent_seller = x.created_at : ' '
        - quote_prices.to_s==' ' && sent_seller.to_s==' '? 
        - dias =  0 : sent_seller.to_s==' '? 
        - dias = ((Time.zone.now - quote_prices)  /86400 ).to_i  : dias = dias = ((sent_seller - quote_prices)  /86400 ).to_i 
        - quantity_difficulty.to_i >= dias.to_i ? estado = 'Se Cumplio' : estado = 'Se Incumplio' 
        - p.try(:difficulty_quote).try(:quantity)?  
        - quantity_difficulty.to_i >= dias.to_i ? estado = 'Se Cumplio' : estado = 'Se Incumplio'  :   estado = ' ' 
                    
        %tr
          %td= p.number
          %td= p.estado_cost
          %td= p.try(:adviser).try(:name)
          %td= p.try(:client).try(:name)
          %td= sent_to_cost
          %td= quote_prices 
          %td
            %span.label.label-info= dias.to_i
          %td= p.try(:difficulty_quote).try(:difficulty_lapse)
          %td= sent_seller
          %td
            -if estado == 'Se Cumplio'
              %span.label.label-success= estado
            -if estado == 'Se Incumplio'
              %span.label.label-danger= estado 
            -if estado == ' '      
              = estado         
          %td= p.cost_observations    
          %td
            %span.label.label-success= p.quote_status
          %td
            = render 'status_changes', :p => p
          %td
            -if  current_user.is?(:vendedor) && p.elaborated? || p.back_to_sales?
              = link_to(edit_quote_path(p), title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }                            
            -if current_user.is?(:vendedor) && p.approved?             
              - if p.production_orders.any?
                = link_to(edit_production_order_path(p.production_orders.first.try(:id)), title: 'Editar Orden de Producción'){ content_tag(:i, '', class:"icon-pencil") }
              - else
                = link_to(new_production_order_path(:quote_id => p), title: 'Agregar Orden de Producción'){ content_tag(:i, '', class:"icon-plus") }
            -if current_user.is?(:vendedor) &&  p.elaborated?
              / = link_to(quote_path(p), method: :delete, title: 'Eliminar', confirm: '¿Desea eliminar la Cotizacion?'){ content_tag(:i, '', class:"icon-remove") }
            = link_to(quote_path(p), title: 'Ver'){ content_tag(:i, '', class:"icon-eye-open") } 
            = link_to(image_tag("pdf-icon.png"), quotes_path(p, format: :pdf))
          

app/views/quotes/_list_cost_costo.html.haml
%table.table.table-condensed.table-striped#tablequotes
  %thead
    %tr
      %th="Cot"        
      %th="Asesor"
      %th="Cliente/Agencia"
      %th="Enviado a Costos"     
      %th="Inicio Costos"     
      %th="Días Restantes"     
      %th="Estado Cotización"               
      %th="Acciones"
      %th=""
  %tbody
    - @quotes.each do |p|
      %tr
        %td= p.number        
        %td= p.adviser.name if p.adviser
        %td= p.try(:client).try(:name)
        %td= l p.sent_to_cost if p.sent_to_cost
        %td= l p.begin_analysis if p.begin_analysis
        %td= p.days_to_end
        %td
          %span.label.label-success= p.quote_status  
        %td
          -if current_user.is?(:costo) && (p.difficulty_quote.nil? || p.coordinator.nil?)
            = link_to(edit_quote_path(p), title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
          -if p.difficulty_quote_id  &&  (p.sent_to_cost?  || p.quote_prices?)
            = link_to(quote_costs_registration_path(p), title: 'Agregar Costos a la Cotizacion'){ content_tag(:i, '', class:"icon-briefcase") }                           
          = link_to(image_tag("pdf-icon.png"), quote_path(p, format: :pdf), target: "_blank") 
          -if current_user.is?(:costo) || current_user.is?(:seguimiento) 
            / = link_to(comments_path(p), title: 'Listar Seguimientos'){ content_tag(:i, '', class:"icon-comments") }
            = link_to(new_comment_path(p), title: 'Nuevo seguimiento'){ content_tag(:i, '', class:"icon-comment") }
        / %td= p.cost_observations   
        %td
          -if p.quote_prices?
            = link_to(sent_seller_quote_path(p), method: :put, data: {confirm: '¿Desea enviar la cotizacion al Vendedor?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
              - content_tag(:i, '') + "Enviar al Vendedor"  
    .clearfix.total-count= pluralize(@quotes.size, 'orden')

app/views/quotes/_status_changes.html.haml
-if current_user.is?(:vendedor)
  -if p.elaborated?  or p.back_to_sales? 
    = link_to(sent_to_cost_quote_path(p), data: {confirm: '¿Desea enviarla a Costos?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Enviar a Costos"
  -if p.elaborated? || p.customer_review? || p.sent_to_cost?
    = link_to(canceled_quote_path(p), data: {confirm: '¿Desea Anular Cotización?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Anular Cotización"                         
  -if p.rejected? && current_user.is?(:costo)
    = link_to(cost_report_quote_path(p), data: {confirm: '¿Desea enviar a Informe de Costos?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Enviar a Informe de Costos" 
-if current_user.is?(:vendedor)
  -if p.sent_seller?
    = link_to(delivered_customer_quote_path(p), data: {confirm: '¿Desea entregarla al Cliente?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Entregar al Cliente"
-if current_user.is?(:costo) || current_user.is?(:seguimiento)
  -if p.quote_prices?
    = link_to(delivered_customer_quote_path(p), data: {confirm: '¿Desea entregarla a Ventas?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Entregar al Vendedor"
  -if p.delivered_customer?  
    = link_to(approved_quote_path(p), data: {confirm: '¿Desea Aprobar Esta Cotización?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "Aprobada"
  -if p.delivered_customer? 
    = link_to(rejected_quote_path(p), data: {confirm: '¿Desea Rechazar Esta Cotización?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
      - content_tag(:i, '') + "No Aprobada"   

app/views/quotes/costs.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(list_cost_quotes_path){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        
    %div.widget-body
      %h3="Registrar Costos de la Cotización"
      %hr
      %div.tab-content

        = simple_form_for(@quote, :url => "/quotes/#{@quote.id}/costs", :method => :put)  do |f|
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span12
              %div.row-fluid
                = render 'form_fields_costs', :f => f                     
                = render 'form_fields_detail_costs', :f => f
                = render 'form_fields_anexos_edit', :f => f 

          %br
          -if current_user.is?(:costo) ||  current_user.is?(:analista)
            -if can? :update, @quote
              -if @quote.sent_to_cost?
                -if @quote.coordinator_id == current_user.id || current_user.is?(:costo)
                  = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
                    - content_tag(:i, '') + "Asignar Precios"   
                  = link_to(back_to_sales_quote_path(@quote), data: {confirm: '¿Desea Devolverla a Venta?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
                    - content_tag(:i, '') + "Devolver a Venta"                       
            
            -if @quote.quote_prices?
              = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok' , data: {confirm: '¿Desea enviar la cotizacion a Seguimiento?'}) do
                - content_tag(:i, '') + "Enviar al Vendedor"                 


          = link_to(list_cost_quotes_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Ir a Lista"
          

   
:javascript
  $(document).on('ready page:load', function () {
    
    $("#adviser_id").prop("disabled",true);
    $("#client_id").prop("disabled",true);    
    $("#agency_id").prop("disabled",true);
    $("#quote_commission_quote").prop("disabled",true);
    $("#quote_method_payment").prop("disabled",true);
    $("#quote_form_delivery").prop("disabled",true);  

  /*fin del document*/      
  });