config/routes.rb
VallaYAviso::Application.routes.draw do
  
  resources :difficulty_quotes

  resources :types_descriptions
  resources :types
  resources :categories
  
  resources :agencies do
    get 'search', on: :collection
  end

  resources :binnacles do
  end

  resources :production_orders do
    get 'search', on: :collection
    get 'quotes_lists', on: :collection
    get 'new_orders', on: :collection
    get 'details', on: :member
    get 'review', on: :member
    get 'sent_to_cost', on: :member
    get 'sent_to_cost_by_price_adjustment', on: :member
    get 'sent_to_production', on: :member
    get 'ended', on: :member
    get 'ended_inventory', on: :member
    get 'ended_machine', on: :member
    get 'ended_warehouse', on: :member
    get 'billing', on: :member     
    get 'billed', on: :member     
    get 'list' => 'production_orders#list'
    resources :production_order_binnacles
  end

  resources :bills do
      get 'search', on: :collection
    end

  resources :remissions do
      get 'search', on: :collection
      get 'sent', on: :member 
    end

  resources :work_orders  do
    get 'search', on: :collection
    get 'deliver', on: :member 
    get 'validate', on: :member 
  end

  resources :quotes do
    get 'search', on: :collection    
    get 'details', on: :member 
    get 'customer_review', on: :member 
    get 'sent_to_cost', on: :member   
    get 'back_to_sales', on: :member 
    get 'canceled', on: :member 
    get 'quote_prices', on: :member 
    put 'sent_seller', on: :member 
    get 'delivered_customer', on: :member 
    get 'approved', on: :member 
    get 'rejected', on: :member 
    get 'cost_report', on: :member 
    get 'costs' => 'quotes#costs', :as => 'costs_registration'  
    put 'costs' => 'quotes#update_costs', :as => 'put_costs_registration'  
    post 'clients' => 'quotes#create_client',   on: :collection      
    get 'list_cost', on: :collection 
  end

  resources :product_orders_materiales do

  end

  resources :products do
    get 'show_category', on: :member 
  end

  resources :product_types do
    get 'show_product', on: :member 
  end 

  resources :products do
    get 'show_category', on: :member 
  end  

  resources :materials_lists do
    get 'sent_to_production', on: :member   
    get 'sent_to_store', on: :member 
  end

  get 'alerts' => 'alerts#show', :as => 'alerts'
  put 'alerts/:id' => 'alerts#update', :as => 'alerts_update'

  resources :departments
  resources :clients
  resources :advisers
  resources :comments 
  resources :materiales
  resources :types_descriptions

  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

   namespace :admin do
    resources :user
  end

   

  root 'welcome#index'

end

app/models/remission.rb
class Remission < ActiveRecord::Base
	self.table_name = "remissions"
  include RemissionsStatus
	belongs_to :administrador
	has_many :remission_details, dependent: :destroy 
	belongs_to :production_order

  before_create :generate_number

	accepts_nested_attributes_for :remission_details,
                                reject_if: lambda { |a| a[:product_id].blank? && a[:quantity].blank?},
                                allow_destroy: true

    validates :date_remission, :presence => true  
    

    attr_accessor :client_name, :client_adress, :client_phone, :reference

     #scope
    scope :by_production_order, ->(production_order) {where("production_order_id = ?",production_order)}
    scope :by_client, ->(client) {joins(:production_order).joins({production_order: [:quote]}).where("quotes.client_id = ?",client)}
	scope :by_quote, ->(quote) {joins(:production_order).where("production_orders.quote_id = ?",quote)}

    #*****************************+TERMINAR VALIDAIOM**************************

    def generate_number
      self.number_remission = (Remission.last.id + 1).to_s.rjust(5,"0")      
    end    

    def remission_status
      if self.status == 'sent'
        return "Enviada"
      else
        return "Elaborada"
      end
    end

    def self.search_by_query(query)
    	result = self.all
    	if !query["production_order"].nil? && !query["production_order"].empty?
    		result = result.by_production_order(query["production_order"])
   		end
   		if !query["client"].nil? && !query["client"].empty?
    		result = result.by_client(query["client"])
   		end
   		if !query["quote"].nil? && !query["quote"].empty?
    		result = result.by_quote(query["quote"])
   		end

    	result
  end
end

app/controllers/remissions_controller.rb
class RemissionsController < ApplicationController
  before_action :set_remission, only: [:show, :edit, :update, :destroy, :sent]
  before_action :set_production_order
  before_action :configure_list

  # GET /remissions
  # GET /remissions.json
  def index
    if @production_order.present?
      @remissions = @production_order.remissions
    else
      @remissions = Remission.all
    end
  end

  # GET /remissions/1
  # GET /remissions/1.json
  def show
  end

  # GET /remissions/new
  def new
    @remission = Remission.new
    @remission.date_remission = Time.zone.now.strftime '%d/%m/%Y'

    if @production_order.present?
      @products = Product.products_of_quote(@production_order.quote)

      
      @remission.client_name = @production_order.try(:quote).try(:client).try(:name)
      @remission.client_adress = @production_order.try(:quote).try(:client).try(:address)
      @remission.client_phone = @production_order.try(:quote).try(:client).try(:phone)
      @remission.reference = @production_order.try(:quote).try(:reference)
      @remission.production_order = @production_order

      @production_order.quote.quote_details.each do |qd|
        remission_detail = @remission.remission_details.build
        remission_detail.quantity = qd.quantity
        remission_detail.remission_id = @remission
        remission_detail.product_id = qd.product_id
      end    
    else
      @products = Product.all
    end   
  end

  # GET /remissions/1/edit
  def edit
    @products = @products = Product.where("id IN (?)", @remission.remission_details.map(&:product_id)) + Product.products_of_quote(@remission.production_order.quote)
    @remission.client_name = @remission.production_order.try(:quote).try(:client).try(:name)
    @remission.client_adress = @remission.production_order.try(:quote).try(:client).try(:address)
    @remission.client_phone = @remission.production_order.try(:quote).try(:client).try(:phone)
    @remission.reference = @remission.production_order.try(:quote).try(:reference)
  end

  # GET /work_orders/search
  def search
    @remissions = Remission.search_by_query(params[:search])
    @production_order = ProductionOrder.find(params[:search][:production_order_id]) if params[:search][:production_order_id].present?
   
    render :index
  end

  #GET /production_orders/:id/review
  def sent
    if @remission.elaborated?
      if @remission.sent_status!
        flash[:notice] = "La Remisión ha cambiado el estatus a Entregada."
        redirect_to remissions_path 
      else
       flash[:warning] = "La Remisión no pudo ser entregada."
       redirect_to remissions_path 
      end
    else
      if @production_order.present?
        @remissions = @production_order.remissions
      else
        @remissions = Remission.all
      end
      render action: 'index' 
    end
  end

  # POST /remissions
  # POST /remissions.json
  def create
    @remission = Remission.new(remission_params)
    @remission.client_name = @production_order.try(:quote).try(:client).try(:name)
    @remission.client_adress = @production_order.try(:quote).try(:client).try(:address)
    @remission.client_phone = @production_order.try(:quote).try(:client).try(:phone)
    @remission.reference = @production_order.try(:quote).try(:reference)
    
    @remission.remission_details.each do |r|
      r.production_order_id = @production_order.try(:id)
    end
    respond_to do |format|
      if @remission.save
        format.html { redirect_to remissions_path(@remission.production_order), notice: "La Remisión fué creada satisfactoriamente con el número #{@remission.number_remission}." }
        format.json { render action: 'show', status: :created, location: @remission }
      else
        format.html { render action: 'new' }
        format.json { render json: @remission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remissions/1
  # PATCH/PUT /remissions/1.json
  def update
    @remission.client_name = @remission.production_order.try(:quote).try(:client).try(:name)
    @remission.client_adress = @remission.production_order.try(:quote).try(:client).try(:address)
    @remission.client_phone = @remission.production_order.try(:quote).try(:client).try(:phone)
    @remission.reference = @remission.production_order.try(:quote).try(:reference)
    @remission.remission_details.each do |r|
      r.production_order_id = @remission.production_order.try(:id)
    end
    respond_to do |format|
      if @remission.update(remission_params)
        format.html { redirect_to remissions_path(@production_order), notice: 'La Remisión fué actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @remission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remissions/1
  # DELETE /remissions/1.json
  def destroy
    @remission.destroy
    respond_to do |format|
      format.html { redirect_to remissions_path(@remission.production_order) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remission
      @remission = Remission.find(params[:id])
    end

    def set_production_order
      @production_order = ProductionOrder.find(params[:production_order_id]) if params[:production_order_id].present?
    end

    def configure_list
      @clients = Client.all
      @quotes = Quote.all
      @production_orders = ProductionOrder.all

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remission_params
      params.require(:remission).permit(:number_remission,:date_remission, :observations, :delivery, :administrador_id, :production_order_id,
        remission_details_attributes: [ :id, :product_id, :quantity, :description, :_destroy]) 
    end
end

app/helpers/remissions_helper.rb
module RemissionsHelper
end

app/views/remissions/_filter.html.haml
= simple_form_for :search, {url: search_remissions_path, method: :get} do |f|
  .span12
    %div.row-fluid
      %div.span5
        = f.select :client, @clients.map{ |c| [c.name, c.id] }, label: false, prompt: "Cliente"
      %div.span5
        = f.select :production_order, @production_orders.map{ |r| [r.number, r.id] }, :label => false, prompt: "Orden de Producción"
      .span5
        = f.select :quote, @quotes.map{ |r| [r.number, r.id] }, :label => false, prompt: "Número de Cotizacion"
      = f.input :production_order_id, as: :hidden, input_html: {maxlength: 255, class: 'span10', value: @production_order.try(:id)}
    %div.row-fluid
      .span12.botton-filter
        = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
          - content_tag(:i, '') + "Buscar"
        = link_to(production_orders_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
          - content_tag(:i, '') + "Cancelar"  

app/views/remissions/_form_fields.html.haml
%div.span12
  %div.row-fluid
    .span6
      = f.input :date_remission, refquired: true, :as => :date_picker, input_html: { class: 'span12'}, label: "Fecha"
    .span6
      = f.input :number_remission, required: false, input_html: {maxlength: 255, class: 'span10', readonly: true}, label: "Número de Remisión"
  %div.row-fluid
    .span6
      - if f.object.production_order.present?
        = f.input :production_order_number, as: :string, input_html: {maxlength: 255, class: 'span10', readonly: true, value: f.object.production_order.present? ? f.object.production_order.number :  ""}, label: "Orden de Producción"
        = f.input :production_order_id, as: :hidden, input_html: {maxlength: 255, class: 'span10', readonly: true}
      - else
        = f.association :production_order, collection: @production_orders.map{ |c| [c.number, c.id] }, input_html: { id: "remission_production_order_id",class: 'span10 field-select'}, label: "Orden de Producción"
    .span6
  %div.row-fluid
    .span6
      = f.input :client_name, as: :string, required: false, input_html: {maxlength: 255, class: 'span10', readonly: true}, label: "Cliente/Agencia"
    .span6
      = f.input :client_phone, as: :string, required: false, input_html: {maxlength: 255, class: 'span10', readonly: true}, label: "Teléfono"
  %div.row-fluid
    .span12
      = f.input :client_adress, as: :string, required: false, input_html: {maxlength: 255, class: 'width-order-large', readonly: true}, label: "Dirección"
  %div.row-fluid
    .span12
      = f.input :reference, as: :string, required: false, input_html: {maxlength: 255, class: 'width-order-large', readonly: true}, label: "Referencia"
  .clearfix
  %hr
  .innerLR
    .widget{:'data-toggle'=>"collapse-widget"}
      .widget-head
        %h4.heading.glyphicons.edit
          %i
          = "Detalle"
      .widget-body
        %h3="Descripción"
        %hr
        %div.tab-content
          %div.well  
            = render 'remission_detail', :f => f

  %hr    
  %div.row-fluid 
    .span12  
      = f.input :delivery, required: true, as: :text, input_html: { class: 'span12 height-large', row:10}, label: "Entrega" 
  %div.row-fluid  
    .span12  
      = f.input :observations, required: true, as: :text, input_html: { class: 'span12 height-large', row:10}, label: "Observaciones"
      = f.input :administrador_id, as: :hidden, input_html: { value: current_user.try(:id)}
  %hr
  
 
:javascript
  $(document).ready(function() {
    $(".field-select").select2({
      placeholder: "Seleccione",
      allowClear: true
    });
  });

  $('#remission_production_order_id').change(function(){ 

      if($(this).val())         {  
        $.get('/production_orders/'+$(this).val()+'/details.json',
          function(data) {                                                                      
            $("#remission_client_name").val(data.client_name);                               
            $("#remission_client_phone").val(data.client_phone);
            $("#remission_client_adress").val(data.client_address);
            $("#remission_reference").val(data.quote_reference);
          });
    }
  });

app/views/remissions/_list.html.haml
- if @remissions.any?
  %table.table.table-condensed.table-striped#tableorders
    %thead
      %tr
        %th="Nùmero de Orden de Producción"  
        %th="Nùmero"  
        %th="Fecha"
        %th="Cliente/Agencia"
        %th="Estatus"
        %th=""
    %tbody
      - @remissions.each do |r|
        %tr
          %td= r.production_order.try(:number)
          %td= r.try(:number_remission)
          %td= r.try(:date_remission)
          %td= r.production_order.try(:quote).try(:client).try(:name)
          %td
            %span.label.label-success= r.remission_status
          %td
            = render 'status_changes', :r => r
            = link_to(edit_remission_path(r, :production_order_id =>@production_order), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
            - if can? :destroy, Remission
              = link_to(remission_path(r, :production_order_id =>@production_order), method: :delete, class: 'pjax', title: 'Eliminar Remisión', data: {confirm: '¿Desea eliminar la Remisión?'}){ content_tag(:i, '', class:"icon-remove") }
- else
  %span
    Sin Remisiones
  %br
  %br
  = link_to(new_remission_path(:production_order_id =>@production_order), class: 'btn btn-icon btn-primary glyphicons circle_ok') do
    - content_tag(:i, '') + "Agregar Nuevo"

          

app/views/remissions/_remission_detail.html.haml
#remission_details
  = f.simple_fields_for :remission_details do |r|
    = render 'remission_detail_fields', :f => r 
  .links
    = link_to_add_association(f, :remission_details,  { class: 'btn btn-icon glyphicons circle_plus btn-success' }){ content_tag('i') + ' Agregar Detalle' }

app/views/remissions/_remission_detail_fields.html.haml
.nested-fields.well  
  .row-fluid
    .span11  
      .span6
        = f.input :product_id, collection: @products, label_method: :name, value_method: :id, :label => 'Producto', prompt: "Producto", input_html: { class: 'width-order-large-nested', :id => 'product_id' }
      .span6
        = f.input :quantity, :label => 'Cantidad', prompt: "Cantidad", input_html: { class: 'span10', :id => 'quantity', type: 'text' }  
      .span8
        = f.input :description, :label => 'Descripción', prompt: "Descripción", input_html: { class: 'span10', :id => 'description', type: 'text' }  
      %br
    .span1
      %br
        = link_to_remove_association "Eliminar", f

app/views/remissions/_status_changes.html.haml
-if r.elaborated? 
  = link_to(sent_remission_path(r), data: {confirm: '¿Desea marcar como entregada la Remisión?'}, class: 'btn btn-icon btn-primary glyphicons circle_ok') do
    - content_tag(:i, '') + "Entregar Remisión"

app/views/remissions/edit.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(remissions_path(:production_order_id => @production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        -if @production_order.present? 
          %li.icon.new_collection_link.active
            = link_to(edit_production_order_path(@production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Ir a la Orden') }
        %li.icon.new_collection_link 
          = link_to(new_remission_path(:production_order_id => @remission.production_order), class: 'pjax', id: "botton"){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %h3="Editar Remisión No "+@remission.try(:number_remission)+". Orden No "+@remission.production_order.try(:number)
      %hr
      %div.tab-content

        = simple_form_for @remission, {url: remission_path, method: :put} do |f|
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span12
              %div.row-fluid
                = render 'form_fields', :f => f 
                              
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(remissions_path(:production_order_id => @production_order), class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"

      

app/views/remissions/index.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(remissions_path(:production_order_id =>@production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_remission_path(:production_order_id =>@production_order)){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }

    %div.widget-body
      %h3="Listado de Remisiones"
      %hr
      %div.tab-content
        %div.list
          %div.well
            .row-fluid.no-margin-bottom
              = render 'filter'
          = flash_messages
          = render 'list'                  



:javascript
  $(document).ready(function() {
    $('#tableorders').DataTable({
        "ordering": false,
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por página",
            "zeroRecords": "No hay registros encontrados",
            "info": "Mostrando página _PAGE_ de _PAGES_",
            "infoEmpty": "No hay registros activos",
            "infoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sSearch":        "Buscar:",
            "oPaginate": {
              "sFirst":    "Primero",
              "sLast":    "Último",
              "sNext":    "Siguiente",
              "sPrevious": "Anterior"
            }
        }
    });
     $("#search_client, #search_production_order, #search_quote").select2({
      allowClear: true
    });
  });

app/views/remissions/new.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(remissions_path(:production_order_id => @production_order || ''), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        - if @production_order.present?
          %li.icon.new_collection_link.active
            = link_to(edit_production_order_path(@production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Ir a la Orden') }
    %div.widget-body
      %h3="Crear Nueva Remisión. #{@production_order.present? ? 'Orden No' +@production_order.try(:number) : '' }"
      %hr
      %div.tab-content

        = simple_form_for @remission, {url: remissions_path, method: :post} do |f|
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span12
              %div.row-fluid
                = render 'form_fields', :f => f 
          
                      
                              
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(remissions_path(:production_order_id => @production_order || '') , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"