config/routes.rb
VallaYAviso::Application.routes.draw do
  
  resources :difficulty_quotes

  resources :types_descriptions
  resources :types
  resources :categories
  
  resources :agencies do
    get 'search', on: :collection
  end

  resources :binnacles do
  end

  resources :production_orders do
    get 'search', on: :collection
    get 'quotes_lists', on: :collection
    get 'new_orders', on: :collection
    get 'details', on: :member
    get 'review', on: :member
    get 'sent_to_cost', on: :member
    get 'sent_to_cost_by_price_adjustment', on: :member
    get 'sent_to_production', on: :member
    get 'ended', on: :member
    get 'ended_inventory', on: :member
    get 'ended_machine', on: :member
    get 'ended_warehouse', on: :member
    get 'billing', on: :member     
    get 'billed', on: :member     
    get 'list' => 'production_orders#list'
    resources :production_order_binnacles
  end

  resources :bills do
      get 'search', on: :collection
    end

  resources :remissions do
      get 'search', on: :collection
      get 'sent', on: :member 
    end

  resources :work_orders  do
    get 'search', on: :collection
    get 'deliver', on: :member 
    get 'validate', on: :member 
  end

  resources :quotes do
    get 'search', on: :collection    
    get 'details', on: :member 
    get 'customer_review', on: :member 
    get 'sent_to_cost', on: :member   
    get 'back_to_sales', on: :member 
    get 'canceled', on: :member 
    get 'quote_prices', on: :member 
    put 'sent_seller', on: :member 
    get 'delivered_customer', on: :member 
    get 'approved', on: :member 
    get 'rejected', on: :member 
    get 'cost_report', on: :member 
    get 'costs' => 'quotes#costs', :as => 'costs_registration'  
    put 'costs' => 'quotes#update_costs', :as => 'put_costs_registration'  
    post 'clients' => 'quotes#create_client',   on: :collection      
    get 'list_cost', on: :collection 
  end

  resources :product_orders_materiales do

  end

  resources :products do
    get 'show_category', on: :member 
  end

  resources :product_types do
    get 'show_product', on: :member 
  end 

  resources :products do
    get 'show_category', on: :member 
  end  

  resources :materials_lists do
    get 'sent_to_production', on: :member   
    get 'sent_to_store', on: :member 
  end

  get 'alerts' => 'alerts#show', :as => 'alerts'
  put 'alerts/:id' => 'alerts#update', :as => 'alerts_update'

  resources :departments
  resources :clients
  resources :advisers
  resources :comments 
  resources :materiales
  resources :types_descriptions

  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

   namespace :admin do
    resources :user
  end

   

  root 'welcome#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	self.table_name = "bills"
	
	belongs_to :administrador
	has_many :bill_details
	belongs_to :production_order

	accepts_nested_attributes_for :bill_details,
                                reject_if: lambda { |a| a[:product_id].blank? && a[:quantity].blank?},
                                allow_destroy: true

    validates :date_bill, :bill_number, :presence => true  
    

    attr_accessor :client_name, :client_adress, :client_phone, :reference

     #scope
    scope :by_production_order, ->(production_order) {where("production_order_id = ?",production_order)}
    scope :by_client, ->(client) {joins(:production_order).joins({production_order: [:quote]}).where("quotes.client_id = ?",client)}
	scope :by_quote, ->(quote) {joins(:production_order).where("production_orders.quote_id = ?",quote)}

    #*****************************+TERMINAR VALIDAIOM**************************
    

    def self.search_by_query(query)
    	result = self.all
    	if !query["production_order"].nil? && !query["production_order"].empty?
    		result = result.by_production_order(query["production_order"])
   		end
   		if !query["client"].nil? && !query["client"].empty?
    		result = result.by_client(query["client"])
   		end
   		if !query["quote"].nil? && !query["quote"].empty?
    		result = result.by_quote(query["quote"])
   		end

    	result
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :set_production_order
  before_action :configure_list

  # GET /bills
  # GET /bills.json
  def index
    if @production_order.present?
      @bills = @production_order.bills
    else
      @bills = Bill.all
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @bill.date_bill = Time.zone.now.strftime '%d/%m/%Y'

    if @production_order.present?
      @products = Product.products_of_quote(@production_order.quote)

      
      @bill.client_name = @production_order.try(:quote).try(:client).try(:name)
      @bill.client_adress = @production_order.try(:quote).try(:client).try(:address)
      @bill.client_phone = @production_order.try(:quote).try(:client).try(:phone)
      @bill.reference = @production_order.try(:quote).try(:reference)
      @bill.production_order = @production_order

      @production_order.quote.quote_details.each do |qd|
        bill_detail = @bill.bill_details.build
        bill_detail.quantity = qd.quantity
        bill_detail.description = qd.description
        bill_detail.bill_id = @bill
        bill_detail.product_id = qd.product_id
        bill_detail.price = qd.price
      end    
    else
      @products = Product.all
    end   
  end

  # GET /work_orders/search
  def search
    @bills = Remission.search_by_query(params[:search])
    @production_order = ProductionOrder.find(params[:search][:production_order_id]) if params[:search][:production_order_id].present?
   
    render :index
  end

  # GET /bills/1/edit
  def edit
    @products = Product.products_of_quote(@bill.production_order.quote) + Product.where("id IN (?)", @bill.bill_details.map(&:product_id))
    
    @bill.client_name = @bill.production_order.try(:quote).try(:client).try(:name)
    @bill.client_adress = @bill.production_order.try(:quote).try(:client).try(:address)
    @bill.client_phone = @bill.production_order.try(:quote).try(:client).try(:phone)
    @bill.reference = @bill.production_order.try(:quote).try(:reference)
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.client_name = @production_order.try(:quote).try(:client).try(:name)
    @bill.client_adress = @production_order.try(:quote).try(:client).try(:address)
    @bill.client_phone = @production_order.try(:quote).try(:client).try(:phone)
    @bill.reference = @production_order.try(:quote).try(:reference)
    
    @bill.bill_details.each do |b|
      b.production_order_id = @production_order.try(:id)
    end
    
    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_path(@bill.production_order), notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    @bill.client_name = @production_order.try(:quote).try(:client).try(:name)
    @bill.client_adress = @production_order.try(:quote).try(:client).try(:address)
    @bill.client_phone = @production_order.try(:quote).try(:client).try(:phone)
    @bill.reference = @production_order.try(:quote).try(:reference)
    @bill.bill_details.each do |b|
      b.production_order_id = @production_order.try(:id)
    end
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_path(@bill.production_order), notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_path(@bill.production_order) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def set_production_order
      @production_order = ProductionOrder.find(params[:production_order_id]) if params[:production_order_id].present?
    end

    def configure_list
      @clients = Client.all
      @quotes = Quote.all
      @production_orders = ProductionOrder.all
      @products = Product.all

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:bill_number,:date_bill, :observations, :administrador_id, :production_order_id,
        bill_details_attributes: [ :id, :product_id, :quantity, :price, :description, :_destroy]) 
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill_detail.html.haml
#bill_details
  = f.simple_fields_for :bill_details do |r|
    = render 'bill_detail_fields', :f => r 
  .links
    = link_to_add_association(f, :bill_details,  { class: 'btn btn-icon glyphicons circle_plus btn-success' }){ content_tag('i') + ' Agregar Detalle' }

app/views/bills/_bill_detail_fields.html.haml
.nested-fields.well  
  .row-fluid
    .span11  
      .span6
        = f.input :product_id, collection: @products, label_method: :name, value_method: :id, :label => 'Producto', prompt: "Producto", input_html: { class: 'width-order-large-nested', :id => 'product_id' }
      .span6
        = f.input :quantity, :label => 'Cantidad', prompt: "Cantidad", input_html: { class: 'span10', :id => 'quantity', type: 'text' } 
      .span6
        = f.input :description, :label => 'Descripción', prompt: "Descripción", input_html: { class: 'span10', :id => 'description', type: 'text' }  
      .span4
        = f.input :price, :label => 'Precio', prompt: "Precio", input_html: { class: 'span10', :id => 'price', type: 'text' }  
      %br
    .span1
      %br
        = link_to_remove_association "Eliminar", f

app/views/bills/_filter.html.haml
= simple_form_for :search, {url: bills_path(@production_order), method: :get} do |f|
  .span12
    %div.row-fluid
      %div.span5
        = f.select :client, @clients.map{ |c| [c.name, c.id] }, label: false, prompt: "Cliente"
      %div.span5
        = f.select :production_order, @production_orders.map{ |r| [r.number, r.id] }, :label => false, prompt: "Orden de Producción"
      .span5
        = f.select :quote, @quotes.map{ |r| [r.number, r.id] }, :label => false, prompt: "Número de Cotizacion"
        = f.input :production_order_id, as: :hidden, input_html: {maxlength: 255, class: 'span10', value: @production_order.try(:id)}
    %div.row-fluid
      .span12.botton-filter
        = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
          - content_tag(:i, '') + "Buscar"
        = link_to(production_orders_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
          - content_tag(:i, '') + "Cancelar"  

app/views/bills/_form_fields.html.haml
%div.span12
  %div.row-fluid
    .span6
      = f.input :date_bill, refquired: true, :as => :date_picker, input_html: { class: 'span12'}, label: "Fecha"
    .span6
      = f.input :bill_number, required: false, input_html: {maxlength: 255, class: 'span10'}, label: "Número de Factura"
  %div.row-fluid
    .span6
      - if f.object.production_order.present?
        = f.input :production_order_number, as: :string, input_html: {maxlength: 255, class: 'span10', readonly: true, value: f.object.production_order.present? ? f.object.production_order.number :  ""}, label: "Orden de Producción"
        = f.input :production_order_id, as: :hidden, input_html: {maxlength: 255, class: 'span10', readonly: true}
      - else
        = f.association :production_order, collection: @production_orders.map{ |c| [c.number, c.id] }, input_html: { id: "bill_production_order_id",class: 'span10 field-select'}, label: "Orden de Producción"
    .span6
  %div.row-fluid
    .span6
      = f.input :client_name, as: :string, required: false, input_html: {maxlength: 255, class: 'span10', readonly: true}, label: "Cliente/Agencia"
    .span6
      = f.input :client_phone, as: :string, required: false, input_html: {maxlength: 255, class: 'span10', readonly: true}, label: "Teléfono"
  %div.row-fluid
    .span12
      = f.input :client_adress, as: :string, required: false, input_html: {maxlength: 255, class: 'width-order-large', readonly: true}, label: "Dirección"
  %div.row-fluid
    .span12
      = f.input :reference, as: :string, required: false, input_html: {maxlength: 255, class: 'width-order-large', readonly: true}, label: "Referencia"
  .clearfix
  %hr
  .innerLR
    .widget{:'data-toggle'=>"collapse-widget"}
      .widget-head
        %h4.heading.glyphicons.edit
          %i
          = "Detalle"
      .widget-body
        %h3="Descripción"
        %hr
        %div.tab-content
          %div.well  
            = render 'bill_detail', :f => f

  %hr    
  %div.row-fluid  
    .span12  
      = f.input :observations, required: true, as: :text, input_html: { class: 'span12 height-large', row:10}, label: "Observaciones"
      = f.input :administrador_id, as: :hidden, input_html: { value: current_user.try(:id)}
  %hr
  
:javascript
  $(document).ready(function() {
    $(".field-select").select2({
      placeholder: "Seleccione",
      allowClear: true
    });
  });

  $('#bill_production_order_id').change(function(){ 

      if($(this).val())         {  
        $.get('/production_orders/'+$(this).val()+'/details.json',
          function(data) {                                                                      
            $("#bill_client_name").val(data.client_name);                               
            $("#bill_client_phone").val(data.client_phone);
            $("#bill_client_adress").val(data.client_address);
            $("#bill_reference").val(data.quote_reference);
          });
    }
  });
 

app/views/bills/_list.html.haml
- if @bills.any?
  %table.table.table-condensed.table-striped#tableorders
    %thead
      %tr
        %th="Nùmero de Orden de Producción"  
        %th="Nùmero"  
        %th="Fecha"
        %th="Cliente/Agencia"
        %th=""
    %tbody
      - @bills.each do |r|
        %tr
          %td= r.production_order.try(:number)
          %td= r.try(:bill_number)
          %td= r.try(:date_bill)
          %td= r.production_order.try(:quote).try(:client).try(:name)
          %td
            = link_to(edit_bill_path(r, :production_order_id =>@production_order), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
            - if can? :destroy, Bill
              = link_to(bill_path(r, :production_order_id =>@production_order), method: :delete, class: 'pjax', title: 'Eliminar Factura', data: {confirm: '¿Desea eliminar la Factura?'}){ content_tag(:i, '', class:"icon-remove") }
- else
  %span
    Sin Remisiones
  %br
  %br
  = link_to(new_bill_path(:production_order_id =>@production_order), class: 'btn btn-icon btn-primary glyphicons circle_ok') do
    - content_tag(:i, '') + "Agregar Nuevo"

app/views/bills/edit.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(bills_path(:production_order_id => @production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        -if @production_order.present? 
          %li.icon.new_collection_link.active
            = link_to(edit_production_order_path(:production_order_id => @production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Ir a la Orden') }
        %li.icon.new_collection_link 
          = link_to(new_bill_path(:production_order_id => @bill.production_order), class: 'pjax', id: "botton"){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %h3="Editar Facturación No "+@bill.try(:bill_number)+". Orden No "+@bill.production_order.try(:number)
      %hr
      %div.tab-content

        = simple_form_for @bill, {url: bill_path, method: :put} do |f|
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span12
              %div.row-fluid
                = render 'form_fields', :f => f 
                              
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(bills_path(:production_order_id => @bill.production_order), class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"

      

app/views/bills/index.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(bills_path(:production_order_id =>@production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_bill_path(:production_order_id =>@production_order)){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }

    %div.widget-body
      %h3="Listado de Facturas"
      %hr
      %div.tab-content
        %div.list
          %div.well
            .row-fluid.no-margin-bottom
              = render 'filter'
          = flash_messages
          = render 'list'                  



:javascript
  $(document).ready(function() {
    $('#tableorders').DataTable({
        "ordering": false,
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por página",
            "zeroRecords": "No hay registros encontrados",
            "info": "Mostrando página _PAGE_ de _PAGES_",
            "infoEmpty": "No hay registros activos",
            "infoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sSearch":        "Buscar:",
            "oPaginate": {
              "sFirst":    "Primero",
              "sLast":    "Último",
              "sNext":    "Siguiente",
              "sPrevious": "Anterior"
            }
        }
    });
     $("#search_client, #search_production_order, #search_quote").select2({
      allowClear: true
    });
  });

app/views/bills/new.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(bills_path(:production_order_id => @production_order || ''), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        - if @production_order.present?
          %li.icon.new_collection_link.active
            = link_to(edit_production_order_path(@production_order), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Ir a la Orden') }
    %div.widget-body
      %h3="Crear Nueva Factura. #{@production_order.present? ? 'Orden No' +@production_order.try(:number) : '' }"
      %hr
      %div.tab-content

        = simple_form_for @bill, {url: bills_path, method: :post} do |f|
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span12
              %div.row-fluid
                = render 'form_fields', :f => f 
          
                      
                              
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(bills_path(:production_order_id => @production_order || '') , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"

      