config/routes.rb
VallaYAviso::Application.routes.draw do
  
  resources :difficulty_quotes

  resources :types_descriptions
  resources :types
  resources :categories
  
  resources :agencies do
    get 'search', on: :collection
  end

  resources :binnacles do
  end

  resources :production_orders do
    get 'search', on: :collection
    get 'quotes_lists', on: :collection
    get 'new_orders', on: :collection
    get 'details', on: :member
    get 'review', on: :member
    get 'sent_to_cost', on: :member
    get 'sent_to_cost_by_price_adjustment', on: :member
    get 'sent_to_production', on: :member
    get 'ended', on: :member
    get 'ended_inventory', on: :member
    get 'ended_machine', on: :member
    get 'ended_warehouse', on: :member
    get 'billing', on: :member     
    get 'billed', on: :member     
    get 'list' => 'production_orders#list'
    resources :production_order_binnacles
  end

  resources :bills do
      get 'search', on: :collection
    end

  resources :remissions do
      get 'search', on: :collection
      get 'sent', on: :member 
    end

  resources :work_orders  do
    get 'search', on: :collection
    get 'deliver', on: :member 
    get 'validate', on: :member 
  end

  resources :quotes do
    get 'search', on: :collection    
    get 'details', on: :member 
    get 'customer_review', on: :member 
    get 'sent_to_cost', on: :member   
    get 'back_to_sales', on: :member 
    get 'canceled', on: :member 
    get 'quote_prices', on: :member 
    put 'sent_seller', on: :member 
    get 'delivered_customer', on: :member 
    get 'approved', on: :member 
    get 'rejected', on: :member 
    get 'cost_report', on: :member 
    get 'costs' => 'quotes#costs', :as => 'costs_registration'  
    put 'costs' => 'quotes#update_costs', :as => 'put_costs_registration'  
    post 'clients' => 'quotes#create_client',   on: :collection      
    get 'list_cost', on: :collection 
  end

  resources :product_orders_materiales do

  end

  resources :products do
    get 'show_category', on: :member 
  end

  resources :product_types do
    get 'show_product', on: :member 
  end 

  resources :products do
    get 'show_category', on: :member 
  end  

  resources :materials_lists do
    get 'sent_to_production', on: :member   
    get 'sent_to_store', on: :member 
  end

  get 'alerts' => 'alerts#show', :as => 'alerts'
  put 'alerts/:id' => 'alerts#update', :as => 'alerts_update'

  resources :departments
  resources :clients
  resources :advisers
  resources :comments 
  resources :materiales
  resources :types_descriptions

  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

   namespace :admin do
    resources :user
  end

   

  root 'welcome#index'

end

app/models/difficulty_quote.rb
class DifficultyQuote < ActiveRecord::Base
  belongs_to :quote

  def difficulty                        
     return "#{self.name} (#{self.quantity} #{self.lapse} #{self.type_lapse})"
  end    

  def difficulty_lapse                      
     return "#{self.quantity} #{self.lapse} #{self.type_lapse}"
  end     

  def difficulty_production
     return "#{self.name}"
  end    

  rails_admin do
    list do
      field :name
      field :quantity
      field :lapse
    end

    edit do
      field :name
      field :quantity
      field :lapse
      field :type_lapse
      field :is_quote
      field :is_production
    end
  end  

end

app/controllers/difficulty_quotes_controller.rb
class DifficultyQuotesController < ApplicationController
  before_action :set_difficulty_quote, only: [:show, :edit, :update, :destroy]

  # GET /difficulty_quotes
  # GET /difficulty_quotes.json
  def index
    @difficulty_quotes = DifficultyQuote.all
  end

  # GET /difficulty_quotes/1
  # GET /difficulty_quotes/1.json
  def show
  end

  # GET /difficulty_quotes/new
  def new
    @difficulty_quote = DifficultyQuote.new
  end

  # GET /difficulty_quotes/1/edit
  def edit
  end

  # POST /difficulty_quotes
  # POST /difficulty_quotes.json
  def create
    @difficulty_quote = DifficultyQuote.new(difficulty_quote_params)

    respond_to do |format|
      if @difficulty_quote.save
        format.html { redirect_to @difficulty_quote, notice: 'Difficulty quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @difficulty_quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @difficulty_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /difficulty_quotes/1
  # PATCH/PUT /difficulty_quotes/1.json
  def update
    respond_to do |format|
      if @difficulty_quote.update(difficulty_quote_params)
        format.html { redirect_to @difficulty_quote, notice: 'Difficulty quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @difficulty_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /difficulty_quotes/1
  # DELETE /difficulty_quotes/1.json
  def destroy
    @difficulty_quote.destroy
    respond_to do |format|
      format.html { redirect_to difficulty_quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_difficulty_quote
      @difficulty_quote = DifficultyQuote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def difficulty_quote_params
      params.require(:difficulty_quote).permit(:name, :quantity, :lapse, :type_lapse)
    end
end

app/helpers/difficulty_quotes_helper.rb
module DifficultyQuotesHelper
end

app/views/difficulty_quotes/_form.html.erb
<%= simple_form_for(@difficulty_quote) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :quantity %>
    <%= f.input :lapse %>
    <%= f.input :type_lapse %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/difficulty_quotes/edit.html.erb
<h1>Editing difficulty_quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @difficulty_quote %> |
<%= link_to 'Back', difficulty_quotes_path %>

app/views/difficulty_quotes/index.html.erb
<h1>Listing difficulty_quotes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Lapse</th>
      <th>Type lapse</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @difficulty_quotes.each do |difficulty_quote| %>
      <tr>
        <td><%= difficulty_quote.name %></td>
        <td><%= difficulty_quote.quantity %></td>
        <td><%= difficulty_quote.lapse %></td>
        <td><%= difficulty_quote.type_lapse %></td>
        <td><%= link_to 'Show', difficulty_quote %></td>
        <td><%= link_to 'Edit', edit_difficulty_quote_path(difficulty_quote) %></td>
        <td><%= link_to 'Destroy', difficulty_quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Difficulty quote', new_difficulty_quote_path %>

app/views/difficulty_quotes/new.html.erb
<h1>New difficulty_quote</h1>

<%= render 'form' %>

<%= link_to 'Back', difficulty_quotes_path %>

app/views/difficulty_quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @difficulty_quote.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @difficulty_quote.quantity %>
</p>

<p>
  <strong>Lapse:</strong>
  <%= @difficulty_quote.lapse %>
</p>

<p>
  <strong>Type lapse:</strong>
  <%= @difficulty_quote.type_lapse %>
</p>

<%= link_to 'Edit', edit_difficulty_quote_path(@difficulty_quote) %> |
<%= link_to 'Back', difficulty_quotes_path %>